// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1eY9jwq48SRjh6h8Vwci7rbVdwjLK6UA',
    appId: '1:433227946187:web:635d5acf6578bb6cc1a34e',
    messagingSenderId: '433227946187',
    projectId: 'flutter-chat-app-6fe7f',
    authDomain: 'flutter-chat-app-6fe7f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-6fe7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIzmhZGKmQPX2997IuHrRIdHZFqR96Oko',
    appId: '1:433227946187:android:58b3199c2a1483b5c1a34e',
    messagingSenderId: '433227946187',
    projectId: 'flutter-chat-app-6fe7f',
    storageBucket: 'flutter-chat-app-6fe7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlBOALZBzO82lKGOwMGPsRMsuSFis22I',
    appId: '1:433227946187:ios:885163ba6e406278c1a34e',
    messagingSenderId: '433227946187',
    projectId: 'flutter-chat-app-6fe7f',
    storageBucket: 'flutter-chat-app-6fe7f.appspot.com',
    iosBundleId: 'com.izmirsoftware.chatApp',
  );
}
